import { Component } from '@angular/core';
import axios from 'axios';

@Component({
  selector: 'app-list-pokemon',
  imports: [],
  templateUrl: './list-pokemon.component.html',
  styleUrl: './list-pokemon.component.scss'
})
export class ListPokemonComponent {
  pokemons: Array<{ id: number, name: string, type: string }> = [];
  pokemonsApi: Array<{ name: string, url: string }> = [];

  constructor() {
    this.pokemons = [
      { id: 1, name: 'Bulbasaur', type: 'Grass/Poison' },
      { id: 2, name: 'Ivysaur', type: 'Grass/Poison' },
      { id: 3, name: 'Venusaur', type: 'Grass/Poison' },
      { id: 4, name: 'Charmander', type: 'Fire' },
      { id: 5, name: 'Charmeleon', type: 'Fire' },
      { id: 6, name: 'Charizard', type: 'Fire/Flying' },
      { id: 7, name: 'Squirtle', type: 'Water' },
      { id: 8, name: 'Wartortle', type: 'Water' },
      { id: 9, name: 'Blastoise', type: 'Water' },
      { id: 10, name: 'Caterpie', type: 'Bug' },
      { id: 11, name: 'Metapod', type: 'Bug' },
      { id: 12, name: 'Butterfree', type: 'Bug/Flying' },
      { id: 13, name: 'Weedle', type: 'Bug/Poison' },
      { id: 14, name: 'Kakuna', type: 'Bug/Poison' },
      { id: 15, name: 'Beedrill', type: 'Bug/Poison' },
      { id: 16, name: 'Pidgey', type: 'Normal/Flying' },
      { id: 17, name: 'Pidgeotto', type: 'Normal/Flying' },
      { id: 18, name: 'Pidgeot', type: 'Normal/Flying' },
      { id: 19, name: 'Rattata', type: 'Normal' },
      { id: 20, name: 'Spearow', type: 'Normal/Flying' },
      { id: 21, name: 'Fearow', type: 'Normal/Flying' },
      { id: 22, name: 'Ekans', type: 'Poison' },
      { id: 23, name: 'Arbok', type: 'Poison' },
      { id: 24, name: 'Pikachu', type: 'Electric' },
      { id: 25, name: 'Raichu', type: 'Electric' },
      { id: 26, name: 'Sandshrew', type: 'Ground' },
      { id: 27, name: 'Sandslash', type: 'Ground' },
      { id: 28, name: 'Nidoran', type: 'Poison' },
      { id: 29, name: 'Nidorina', type: 'Poison' },
      { id: 30, name: 'Nidoqueen', type: 'Poison/Ground' },
      { id: 31, name: 'Nidoran', type: 'Poison' },
      { id: 32, name: 'Nidorino', type: 'Poison' },
      { id: 33, name: 'Nidoking', type: 'Poison/Ground' },
      { id: 34, name: 'Clefairy', type: 'Fairy' },
      { id: 35, name: 'Clefable', type: 'Fairy' },
      { id: 36, name: 'Vulpix', type: 'Fire' },
      { id: 37, name: 'Ninetales', type: 'Fire' },
      { id: 38, name: 'Jigglypuff', type: 'Normal/Fairy' },
      { id: 39, name: 'Wigglytuff', type: 'Normal/Fairy' },
      { id: 40, name: 'Zubat', type: 'Poison/Flying' },
      { id: 41, name: 'Golbat', type: 'Poison/Flying' },
      { id: 42, name: 'Oddish', type: 'Grass/Poison' },
      { id: 43, name: 'Gloom', type: 'Grass/Poison' },
      { id: 44, name: 'Vileplume', type: 'Grass/Poison' },
      { id: 45, name: 'Paras', type: 'Bug/Grass' },
      { id: 46, name: 'Parasect', type: 'Bug/Grass' },
      { id: 47, name: 'Venonat', type: 'Bug/Poison' },
      { id: 48, name: 'Venomoth', type: 'Bug/Poison' },
      { id: 49, name: 'Diglett', type: 'Ground' },
      { id: 50, name: 'Dugtrio', type: 'Ground' },
      { id: 51, name: 'Meowth', type: 'Normal' },
      { id: 52, name: 'Persian', type: 'Normal' },
      { id: 53, name: 'Psyduck', type: 'Water' },
      { id: 54, name: 'Golduck', type: 'Water' },
      { id: 55, name: 'Mankey', type: 'Fighting' },
      { id: 56, name: 'Primeape', type: 'Fighting' },
      { id: 57, name: 'Growlithe', type: 'Fire' },
      { id: 58, name: 'Arcanine', type: 'Fire' },
      { id: 59, name: 'Poliwag', type: 'Water' },
      { id: 60, name: 'Poliwhirl', type: 'Water' },
      { id: 61, name: 'Poliwrath', type: 'Water/Fighting' },
      { id: 62, name: 'Abra', type: 'Psychic' },
      { id: 63, name: 'Kadabra', type: 'Psychic' },
      { id: 64, name: 'Alakazam', type: 'Psychic' },
      { id: 65, name: 'Machop', type: 'Fighting' },
      { id: 66, name: 'Machoke', type: 'Fighting' },
      { id: 67, name: 'Machamp', type: 'Fighting' },
      { id: 68, name: 'Bellsprout', type: 'Grass/Poison' },
      { id: 69, name: 'Weepinbell', type: 'Grass/Poison' },
      { id: 70, name: 'Victreebel', type: 'Grass/Poison' },
      { id: 71, name: 'Tentacool', type: 'Water/Poison' },
      { id: 72, name: 'Tentacruel', type: 'Water/Poison' },
      { id: 73, name: 'Geodude', type: 'Rock/Ground' },
      { id: 74, name: 'Graveler', type: 'Rock/Ground' },
      { id: 75, name: 'Golem', type: 'Rock/Ground' },
      { id: 76, name: 'Ponyta', type: 'Fire' },
      { id: 77, name: 'Rapidash', type: 'Fire' },
      { id: 78, name: 'Slowpoke', type: 'Water' },
      { id: 79, name: 'Slowbro', type: 'Water/Psychic' },
      { id: 80, name: 'Magnemite', type: 'Electric/Steel' },
      { id: 81, name: 'Magneton', type: 'Electric/Steel' },
      { id: 82, name: 'Farfetchd', type: 'Normal/Flying' },
      { id: 83, name: 'Doduo', type: 'Normal/Flying' },
      { id: 84, name: 'Dodrio', type: 'Normal/Flying' },
      { id: 85, name: 'Seel', type: 'Water' },
      { id: 86, name: 'Dewgong', type: 'Water/Ice' },
      { id: 87, name: 'Grimer', type: 'Poison' },
      { id: 88, name: 'Muk', type: 'Poison' },
      { id: 89, name: 'Shellder', type: 'Water' },
      { id: 90, name: 'Cloyster', type: 'Water/Ice' },
      { id: 91, name: 'Gastly', type: 'Ghost/Poison' },
      { id: 92, name: 'Haunter', type: 'Ghost/Poison' },
      { id: 93, name: 'Gengar', type: 'Ghost/Poison' },
      { id: 94, name: 'Onix', type: 'Rock/Ground' },
      { id: 95, name: 'Drowzee', type: 'Psychic' },
      { id: 96, name: 'Hypno', type: 'Psychic' },
      { id: 97, name: 'Krabby', type: 'Water' },
      { id: 98, name: 'Kingler', type: 'Water' },
      { id: 99, name: 'Voltorb', type: 'Electric' },
      { id: 100, name: 'Electrode', type: 'Electric' },
      { id: 101, name: 'Exeggcute', type: 'Grass/Psychic' },
      { id: 102, name: 'Exeggutor', type: 'Grass/Psychic' },
      { id: 103, name: 'Cubone', type: 'Ground' },
      { id: 104, name: 'Marowak', type: 'Fire/Ground' },
      { id: 105, name: 'Hitmonlee', type: 'Fighting' },
      { id: 106, name: 'Hitmonchan', type: 'Fighting' },
      { id: 107, name: 'Lickitung', type: 'Normal' },
      { id: 108, name: 'Koffing', type: 'Poison' },
      { id: 109, name: 'Weezing', type: 'Poison' },
      { id: 110, name: 'Rhyhorn', type: 'Ground/Rock' },
      { id: 111, name: 'Rhydon', type: 'Ground/Rock' },
      { id: 112, name: 'Chansey', type: 'Normal' },
      { id: 113, name: 'Tangela', type: 'Grass' },
      { id: 114, name: 'Kangaskhan', type: 'Normal' },
      { id: 115, name: 'Horsea', type: 'Water' },
      { id: 116, name: 'Seadra', type: 'Water' },
      { id: 117, name: 'Goldeen', type: 'Water' },
      { id: 118, name: 'Seaking', type: 'Water' },
      { id: 119, name: 'Staryu', type: 'Water' },
      { id: 120, name: 'Starmie', type: 'Water/Psychic' },
      { id: 121, name: 'Mr. Mime', type: 'Psychic/Fairy' },
      { id: 122, name: 'Scyther', type: 'Bug/Flying' },
      { id: 123, name: 'Jynx', type: 'Ice/Psychic' },
      { id: 124, name: 'Electabuzz', type: 'Electric' },
      { id: 125, name: 'Magmar', type: 'Fire' },
      { id: 126, name: 'Pinsir', type: 'Bug' },
      { id: 127, name: 'Tauros', type: 'Normal' },
      { id: 128, name: 'Magikarp', type: 'Water' },
      { id: 129, name: 'Gyarados', type: 'Water/Flying' },
      { id: 130, name: 'Lapras', type: 'Water/Ice' },
      { id: 131, name: 'Ditto', type: 'Normal' },
      { id: 132, name: 'Eevee', type: 'Normal' },
      { id: 133, name: 'Vaporeon', type: 'Water' },
      { id: 134, name: 'Jolteon', type: 'Electric' },
      { id: 135, name: 'Flareon', type: 'Fire' },
      { id: 136, name: 'Porygon', type: 'Normal' },
      { id: 137, name: 'Omanyte', type: 'Rock/Water' },
      { id: 138, name: 'Omastar', type: 'Rock/Water' },
      { id: 139, name: 'Kabuto', type: 'Rock/Water' },
      { id: 140, name: 'Kabutops', type: 'Rock/Water' },
      { id: 141, name: 'Aerodactyl', type: 'Rock/Flying' },
      { id: 142, name: 'Snorlax', type: 'Normal' },
      { id: 143, name: 'Articuno', type: 'Ice/Flying' },
      { id: 144, name: 'Zapdos', type: 'Electric/Flying' },
      { id: 145, name: 'Moltres', type: 'Fire/Flying' },
      { id: 146, name: 'Dratini', type: 'Dragon' },
      { id: 147, name: 'Dragonair', type: 'Dragon' },
      { id: 148, name: 'Dragonite', type: 'Dragon/Flying' },
      { id: 149, name: 'Mewtwo', type: 'Psychic' },
      { id: 150, name: 'Mew', type: 'Psychic' }
    ];
  }

  async fetchPokemons() {
    try {
      const response = await axios.get('https://pokeapi.co/api/v2/pokemon?limit=10'); // เรียก API
      this.pokemonsApi = response.data.results;
    } catch (error) {
      console.error('Error fetching Pokémons:', error);
    }
  }

  ngOnInit() {
    this.fetchPokemons(); // โหลดข้อมูลเมื่อ Component เริ่มทำงาน
  }
}
